//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UninstallCommandStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UninstallCommandStrings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.UninstallCommandStrings", typeof(UninstallCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string Description => ResourceManager.GetString("Description", resourceCulture);
        internal static string PrOptionDescription => ResourceManager.GetString("PrOptionDescription", resourceCulture);
        internal static string PrefixArgumentDescription => ResourceManager.GetString("PrefixArgumentDescription", resourceCulture);
        internal static string YesOptionDescription => ResourceManager.GetString("YesOptionDescription", resourceCulture);
        internal static string DryRunOptionDescription => ResourceManager.GetString("DryRunOptionDescription", resourceCulture);
        internal static string MissingTargetError => ResourceManager.GetString("MissingTargetError", resourceCulture);
        internal static string ConflictingTargetsError => ResourceManager.GetString("ConflictingTargetsError", resourceCulture);
        internal static string PrefixHeader => ResourceManager.GetString("PrefixHeader", resourceCulture);
        internal static string RouteHeader => ResourceManager.GetString("RouteHeader", resourceCulture);
        internal static string PlannedRemovalsHeader => ResourceManager.GetString("PlannedRemovalsHeader", resourceCulture);
        internal static string ManualStepsHeader => ResourceManager.GetString("ManualStepsHeader", resourceCulture);
        internal static string DryRunFooter => ResourceManager.GetString("DryRunFooter", resourceCulture);
        internal static string ConfirmPrompt => ResourceManager.GetString("ConfirmPrompt", resourceCulture);
        internal static string UserDeclinedMessage => ResourceManager.GetString("UserDeclinedMessage", resourceCulture);
        internal static string NothingToDoMessage => ResourceManager.GetString("NothingToDoMessage", resourceCulture);
        internal static string RefusalMessage => ResourceManager.GetString("RefusalMessage", resourceCulture);
        internal static string CompletedMessage => ResourceManager.GetString("CompletedMessage", resourceCulture);
        internal static string PartialFailureMessage => ResourceManager.GetString("PartialFailureMessage", resourceCulture);
    }
}
